name: Trigger auto deployment for front-intelli3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/front-intelli3-AutoDeployTrigger-8aab0c7e-e5cc-494d-8aff-0198c46dba2b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FRONTINTELLI3_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FRONTINTELLI3_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FRONTINTELLI3_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrtccfrontintelli3.azurecr.io
          registryUsername: ${{ secrets.FRONTINTELLI3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRONTINTELLI3_REGISTRY_PASSWORD }}
          containerAppName: front-intelli3
          resourceGroup: TCC_intelli
          imageToBuild: acrtccfrontintelli3.azurecr.io/front-intelli3:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


